#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import requests
import xmltodict
from attrdict import AttrDict
import json

here = os.path.dirname(os.path.realpath(__file__)) + '/../'

def main():
  lat = 47.60246
  lon = -122.31353759765625
  url = "http://forecast.weather.gov/MapClick.php?lat={}&lon={}&FcstType=digitalDWML".format(lat,lon)
  write_json(fetch(url), 'assets/data.json')

def fetch(url):
  r = requests.get(url)
  data = AttrDict(xmltodict.parse(r.text)).dwml.data

  return AttrDict({
    't': data['time-layout']['start-valid-time'],
#    'Dew Point': ['º', [int(x) for x in data.parameters.temperature[0].value]],
    'Temperature': ['º', [int(x) for x in data.parameters.temperature[2].value]],
    'Wind Speed': ['mph', [int(x) for x in data.parameters['wind-speed'][0]['value']]],
    'Cloud Cover': ['%', [int(x) for x in data.parameters['cloud-amount']['value']]],
    'Chance Precipitation': ['%', [int(x) for x in data.parameters['probability-of-precipitation']['value']]],
#    'Relative Humidity': ['%', [int(x) for x in data.parameters['humidity']['value']]],
  })

def write_json(data, filename, compress=False):
  with open(here + filename, 'w') as f:
    json.dump(data, f)

if __name__ == '__main__':
  main()
